name: Waka Readme

on:
  schedule:
    - cron: '59 11 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  update-readme:
    name: WakaReadme Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          API_BASE_URL: https://wakatime.com/api
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ### content
          REPOSITORY: vietbui1999ru/vietbui1999ru
          SECTION_NAME: waka # optional
          BLOCKS: ->
          CODE_LANG: python typescript javascript bash csh c rust go hcl cmake shell # optional
          time_range: all_time # optional
          LANG_COUNT: 4 # optional
          SHOW_MASKED_TIME: true
          IGNORED_LANGUAGES: YAML JSON TOML # optional
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: master # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: vietbui1999ru # optional
          AUTHOR_NAME: Viet Bui # optional
          AUTHOR_EMAIL: buiquocviet99@gmail.com # optional
          # you can populate email-id with secrets instead
